version: '3.7'

services:
    rabbitmq:
        image: earnestng/esd_stock:rabbitmq
        container_name: rabbitmq
        # ports:
        #     - "5673:5672"
        #     - "15673:15672"
        networks:
            - broker_network
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest  
    user:
        build: ./user/      #image: earnestng/esd_stock:user
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/user"
        ports:
            - "5010:5010"
    trading:            
        build: ./trading/   #image: earnestng/esd_stock:trading
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/transaction"
        ports:
            - "5020:5020"
    alerting:           
        build: ./alerting/  #image: earnestng/esd_stock:alerting
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/alert"
        ports:
            - "5030:5030"
    stock:              
        build: ./stock/     #image: earnestng/esd_stock:stock
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/stock"
        ports:
            - "6010:6010"
    news:               
        build: ./news/      #image: earnestng/esd_stock:news
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/news"
        ports:
            - "6020:6020"
networks:
    broker_network: 
        driver: "bridge"