version: '3.7'

###############################################################
# Current Port Allocation:
    # user      5010:5010
    # trading   5020:5020
    # alerting  5030:5030
    # stock     6010:6010
    # news      6020:6020
###############################################################

services:
    rabbitmq:
        image: earnestng/esd_stock:rabbitmq
        container_name: rabbitmq
        # ports:
        #     - "5673:5672"
        #     - "15673:15672"
        networks:
            - broker_network
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest  

    ############################################################
    ##  if we want to run a database inside our docker :)
    # db: 
    #     image: mysql
    #     ports: 
    #         - "3308:3306"
    #     expose:
    #         - '3308'
    #     volumes:
    #         - ./sql-files:/docker-entrypoint-initdb.d
    ############################################################

    user1:
        #build: ./user/      
        image: earnestng/esd_stock:user
        container_name: user1
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/user"
        ports:
            - "5010:5010"
    user2:
        #build: ./user/      
        image: earnestng/esd_stock:user
        container_name: user2
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/user"
        # ports:
        #     - "5010:5010"
    trading1:            
        #build: ./trading/   
        image: earnestng/esd_stock:trading
        container_name: trading1
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/transaction"
        ports:
            - "5020:5020"
    trading2:            
        #build: ./trading/   
        image: earnestng/esd_stock:trading
        container_name: trading2
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/transaction"
        # ports:
        #     - "5020:5020"
    alerting:           
        #build: ./alerting/  
        image: earnestng/esd_stock:alerting
        container_name: alerting1
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/alert"
        ports:
            - "5030:5030"
    stock:              
        #build: ./stock/     
        image: earnestng/esd_stock:stock
        container_name: stock1
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/stock"
        ports:
            - "6010:6010"
    news:               
        #build: ./news/      
        image: earnestng/esd_stock:news
        container_name: news1
        environment: 
            - "dbURL=mysql+mysqlconnector://root@host.docker.internal:3306/news"
        ports:
            - "6020:6020"
networks:
    broker_network: 
        driver: "bridge"