FROM python:3
WORKDIR /usr/src/app
COPY . .
RUN apt-get update && apt-get install -y dos2unix
COPY script.sh /script.sh
RUN dos2unix /script.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt
CMD ./script.sh